name: Android CI

on: [release]

jobs:

  android-ci:
    runs-on: ubuntu-latest
    container: code0987/android-ci:latest

    steps:
    - uses: actions/checkout@v1

    - name: build
      run: |
        npm install
        ls 
        export GRADLE_USER_HOME=`pwd`.gradle
        chmod +x ./gradlew
        ./gradlew build
        ./gradlew assembleRelease
        cd app/build/outputs/apk/blue/release
        find . -print
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
          args: app/build/outputs/apk/blue/release/app-blue-release-unsigned.apk
      env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
