name: Android CI

on: [release]

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  android-ci:
    runs-on: ubuntu-latest
    container: code0987/android-ci:latest

    steps:
    - uses: actions/checkout@v1

    - name: build
      run: |
        npm install
        ls 
        export GRADLE_USER_HOME=`pwd`.gradle
        chmod +x ./gradlew
        ./gradlew build
        ./gradlew assembleRelease
        ./upload-to-release app/build/outputs/apk/blue/release/app-blue-release-unsigned.apk

