name: Android CI

on: [release]

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
  RELESE_PASSCODE: ${{ secrets.RELESE_PASSCODE }} 
jobs:
  android-ci:
    runs-on: ubuntu-latest
    container: code0987/android-ci:latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          export GRADLE_USER_HOME=`pwd`.gradle
          chmod +x ./gradlew
          ./gradlew build
          ./gradlew assembleRelease
      - name: upload to release
        run: |
          chmod +x ./upload-to-release
          ./upload-to-release app/build/outputs/apk/blue/release/app-blue-release-unsigned.apk application/vnd.android.package-archive
      - name: restore release keystore
        run: |
            echo "${{ secrets.RELEASE_TOKEN }}" > release.keystore.asc
            gpg -d --passphrase "${{  secrets.RELESE_PASSCODE }}" --batch release.keystore.asc > release.keystore
            ls

