name: Android CI

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
  RELESE_PASSCODE: ${{ secrets.RELESE_PASSCODE }} 
  GITHUB_RELEASE_ID: ${{ github.event.release.id }}
  GITHUB_RELEASE_DRAFT: ${{ github.event.release.draft }}
jobs:
  android-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: restore release keystore
        run: |
            export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools
            echo "${{ secrets.RELEASE_TOKEN }}" > release.keystore.asc
            gpg -d --passphrase "${{  secrets.RELESE_PASSCODE }}" --batch release.keystore.asc > release.keystore
            ls 
            jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore release.keystore app-green-release-unsigned.apk alias -storepass ${{ secrets.RELESE_PASSCODE }}
            ls
            zipalign -v 4 app-green-release-unsigned.apk app-green-release-signed.apk
            apksigner verify app-green-release-signed.apk
            ls


