name: Android CI

on: [release]

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
  RELESE_PASSCODE: ${{ secrets.RELESE_PASSCODE }} 
jobs:
  android-ci:
    runs-on: ubuntu-latest

    steps:
    - name: build
      run: |
        ./upload-to-release gradlew.bat
    - name: restore release keystore
      run: |
          echo "${{ secrets.RELEASE_TOKEN }}" > release.keystore.asc
          gpg -d --passphrase "${{  secrets.RELESE_PASSCODE }}" --batch release.keystore.asc > release.keystore
          ls
    
