name: Android CI

on: [release]

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
  RELESE_PASSCODE: ${{ secrets.RELESE_PASSCODE }} 
jobs:
  android-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          chmod +x ./upload-to-release
          ./upload-to-release tusky-v13.1.apk application/vnd.android.package-archive
      - name: restore release keystore
        run: |
            echo "${{ secrets.RELEASE_TOKEN }}" > release.keystore.asc
            gpg -d --passphrase "${{  secrets.RELESE_PASSCODE }}" --batch release.keystore.asc > release.keystore
            ls

